service: wishly-server

frameworkVersion: '4'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-prune-plugin
#  - serverless-domain-manager

custom:
  prune:
    automatic: true
    number: 2
#  customDomain:
#    domainName: *
#    basePath: auth
#    stage: ${self:provider.stage}
#    createRoute53Record: true
#    certificateName: *

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  profile: serverlessUser
  timeout: 20
  environment:
    MONGODB_USER: ${env:MONGODB_USER}
    MONGODB_PASSWORD: ${env:MONGODB_PASSWORD}
    MONGODB_URL: ${env:MONGODB_URL}
    MONGODB_DB: ${env:MONGODB_DB}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SEECRET: ${env:COGNITO_CLIENT_SEECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource:
        - arn:aws:cognito-idp:us-east-1:884252207764:userpool/us-east-1_iLGqg20bi

#====================================================================
functions:
  registerUser:
    handler: src/handlers/authHandler.registerHandler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  confirmRegister:
    handler: src/handlers/authHandler.confirmRegisterHandler
    events:
      - http:
          path: auth/register/confirm
          method: post
          cors: true

  updateUserGroup:
    handler: src/handlers/authHandler.updateGroupHandler
    events:
      - http:
          path: auth/updateGroup
          method: post
          cors: true

  loginUser:
    handler: src/handlers/authHandler.loginHandler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  logoutUser:
    handler: src/handlers/authHandler.logoutHandler
    events:
      - http:
          path: auth/logout
          method: post
          cors: true

  #====================================================================
  registerUserCustom:
    handler: src/handlers/userHandler.registerUserHandler
    events:
      - http:
          path: users/register
          method: post
          cors: true

  loginWithApple:
    handler: src/handlers/userHandler.loginWithAppleHandler
    events:
      - http:
          path: users/login/apple
          method: post
          cors: true

  getUserById:
    handler: src/handlers/userHandler.getUserByIdHandler
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

  updateUserProfile:
    handler: src/handlers/userHandler.updateUserProfileHandler
    events:
      - http:
          path: users/{id}
          method: put
          cors: true

  deleteUser:
    handler: src/handlers/userHandler.deleteUserHandler
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true

  #====================================================================

  createCollection:
    handler: src/handlers/collectionHandler.createCollectionHandler
    events:
      - http:
          path: collections
          method: post
          cors: true

  getCollectionById:
    handler: src/handlers/collectionHandler.getCollectionByIdHandler
    events:
      - http:
          path: collections/{id}
          method: get
          cors: true

  updateCollection:
    handler: src/handlers/collectionHandler.updateCollectionHandler
    events:
      - http:
          path: collections/{id}
          method: put
          cors: true

  deleteCollection:
    handler: src/handlers/collectionHandler.deleteCollectionHandler
    events:
      - http:
          path: collections/{id}
          method: delete
          cors: true

  getAllCollections:
    handler: src/handlers/collectionHandler.getAllCollectionsHandler
    events:
      - http:
          path: collections
          method: get
          cors: true

  addViewUser:
    handler: src/handlers/collectionHandler.addViewUserHandler
    events:
      - http:
          path: collections/{id}/view
          method: post
          cors: true

  addEditUser:
    handler: src/handlers/collectionHandler.addEditUserHandler
    events:
      - http:
          path: collections/{id}/edit
          method: post
          cors: true

  removeViewUser:
    handler: src/handlers/collectionHandler.removeViewUserHandler
    events:
      - http:
          path: collections/{id}/view
          method: delete
          cors: true

  removeEditUser:
    handler: src/handlers/collectionHandler.removeEditUserHandler
    events:
      - http:
          path: collections/{id}/edit
          method: delete
          cors: true

  cloneCollection:
    handler: src/handlers/collectionHandler.cloneCollectionHandler
    events:
      - http:
          path: collections/{id}/clone
          method: post
          cors: true

  #====================================================================

  createItem:
    handler: src/handlers/itemHandler.createItemHandler
    events:
      - http:
          path: collections/{id}/items
          method: post
          cors: true

  getItemById:
    handler: src/handlers/itemHandler.getItemByIdHandler
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  updateItem:
    handler: src/handlers/itemHandler.updateItemHandler
    events:
      - http:
          path: items/{id}
          method: put
          cors: true

  deleteItem:
    handler: src/handlers/itemHandler.deleteItemHandler
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true

  getAllItems:
    handler: src/handlers/itemHandler.getAllItemsHandler
    events:
      - http:
          path: collections/{id}/items
          method: get
          cors: true

  markItemCompleted:
    handler: src/handlers/itemHandler.markItemCompletedHandler
    events:
      - http:
          path: items/{id}/complete
          method: post
          cors: true

  markItemUncompleted:
    handler: src/handlers/itemHandler.markItemUncompletedHandler
    events:
      - http:
          path: items/{id}/uncomplete
          method: post
          cors: true

  toggleItemStatus:
    handler: src/handlers/itemHandler.toggleItemStatusHandler
    events:
      - http:
          path: items/{id}/toggle
          method: post
          cors: true

  #====================================================================
